AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Bestseller list stuff

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Api:
    # API Gateway endpoint type: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-restapi-endpointconfiguration.html
    EndpointConfiguration: REGIONAL

    # Cross Origin Resources Sharing (CORS): https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-api-corsconfiguration.html
    Cors:
      AllowMethods: "'GET, PUT, OPTIONS, POST, DELETE'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token,X-Amz-User-Agent'"
      AllowOrigin: "'*'"
    Function:
      Runtime: nodejs12.x
Resources:
  APIInvokeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: bestseller-invoke-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: InvokeAPI
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "execute-api:Invoke"
                Resource: !Sub arn:${AWS::Partition}:execute-api:${AWS::Region}:${AWS::AccountId}:*:*
  BestSellerDataBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: Private
      BucketName: best-seller-data-bucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  GetBestsellerList:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    # DependsOn:
    #   - APIInvokeRole
    #   - submissionTable
    Properties:
      FunctionName: get-bestseller-list
      CodeUri: get-bestseller-list/
      Description: Gets the bestseller list from the nyt api.
      Handler: app.handler
      Timeout: 30
      Events:
        GetBestSellerList:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /BestSellerLists/{date}/{listName}
            Method: get
            Auth:
              InvokeRole: !GetAtt APIInvokeRole.Arn
            RequestParameters: # Used by Javascript SDK generated by API Gateway
              - method.request.path.submissionID:
                  Required: true
              - method.request.path.date:
                  Required: true
      Policies:
        - Statement:
            - Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Effect: Allow
              Resource: "*"
        - Statement:
            - Action:
                - s3:putObject
              Effect: Allow
              Resource: !Sub arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${BestSellerDataBucket}
        - Statement:
            - Action:
                - ssm:GetParameters
              Effect: Allow
              Resource: "*"
  GetBestsellerListLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn:
      - GetBestsellerList
    Properties:
      LogGroupName: !Sub /aws/lambda/${GetBestsellerList}
      RetentionInDays: 30
  GetBestsellerListNames:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    # DependsOn:
    #   - APIInvokeRole
    #   - submissionTable
    Properties:
      FunctionName: get-bestseller-list-names
      CodeUri: get-bestseller-list-names/
      Description: Gets the bestseller list from the nyt api.
      Handler: app.handler
      Timeout: 30
      Events:
        GetBestSellerListNames:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /BestSellerLists/Names/
            Method: get
            Auth:
              InvokeRole: !GetAtt APIInvokeRole.Arn
            RequestParameters: # Used by Javascript SDK generated by API Gateway
              - method.request.path.submissionID:
                  Required: true
      Policies:
        - Statement:
            - Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Effect: Allow
              Resource: "*"
        - Statement:
            - Action:
                - ssm:GetParameters
              Effect: Allow
              Resource: "*"
  GetBestsellerListNamesLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn:
      - GetBestsellerListNames
    Properties:
      LogGroupName: !Sub /aws/lambda/${GetBestsellerListNames}
      RetentionInDays: 30
