AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Pythia API

  '
Resources:
  BestSellerDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: best-seller-data-bucket
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
